public enum HumanBoneType
{
    Hips,
    LeftUpperLeg,
    RightUpperLeg,
    LeftLowerLeg,
    RightLowerLeg,
    LeftFoot,
    RightFoot,
    Spine,
    Chest,
    Neck,
    Head,
    LeftShoulder,
    RightShoulder,
    LeftUpperArm,
    RightUpperArm,
    LeftLowerArm,
    RightLowerArm,
    LeftHand,
    RightHand,
    LeftToes,
    RightToes,
    LeftEye,
    RightEye,
    Jaw,

    // Metacarpal => Proximal => Distal
    LeftThumbMetacarpal,
    LeftThumbProximal,
    // LeftThumbIntermediate (vrm-0.x)
    LeftThumbDistal,
    LeftIndexProximal,
    LeftIndexIntermediate,
    LeftIndexDistal,
    LeftMiddleProximal,
    LeftMiddleIntermediate,
    LeftMiddleDistal,
    LeftRingProximal,
    LeftRingIntermediate,
    LeftRingDistal,
    LeftLittleProximal,
    LeftLittleIntermediate,
    LeftLittleDistal,
    // Metacarpal => Proximal => Distal
    RightThumbMetacarpal,
    RightThumbProximal,
    // RightThumbIntermediate (vrm-0.x)
    RightThumbDistal,
    RightIndexProximal,
    RightIndexIntermediate,
    RightIndexDistal,
    RightMiddleProximal,
    RightMiddleIntermediate,
    RightMiddleDistal,
    RightRingProximal,
    RightRingIntermediate,
    RightRingDistal,
    RightLittleProximal,
    RightLittleIntermediate,
    RightLittleDistal,
    UpperChest,
}

public static class HumanBoneHeadTailPairs
{
    public static readonly (HumanBoneType, HumanBoneType)[] Values =
    [
        (HumanBoneType.Hips, HumanBoneType.LeftUpperLeg),
        (HumanBoneType.LeftUpperLeg, HumanBoneType.LeftLowerLeg),
        (HumanBoneType.LeftLowerLeg, HumanBoneType.LeftFoot),
        (HumanBoneType.LeftLowerLeg, HumanBoneType.LeftToes),
        //
        (HumanBoneType.Hips, HumanBoneType.RightUpperLeg),
        (HumanBoneType.RightUpperLeg, HumanBoneType.RightLowerLeg),
        (HumanBoneType.RightLowerLeg, HumanBoneType.RightFoot),
        (HumanBoneType.RightLowerLeg, HumanBoneType.RightToes),
        //
        (HumanBoneType.Hips, HumanBoneType.Spine),
        (HumanBoneType.Spine, HumanBoneType.Chest),
        (HumanBoneType.Chest, HumanBoneType.UpperChest),
        (HumanBoneType.UpperChest, HumanBoneType.Neck),
        (HumanBoneType.Neck, HumanBoneType.Head),
        (HumanBoneType.Head, HumanBoneType.LeftEye),
        (HumanBoneType.Head, HumanBoneType.RightEye),
        (HumanBoneType.Head, HumanBoneType.Jaw),
        //
        (HumanBoneType.UpperChest, HumanBoneType.LeftShoulder),
        (HumanBoneType.LeftShoulder, HumanBoneType.LeftUpperArm),
        (HumanBoneType.LeftUpperArm, HumanBoneType.LeftLowerArm),
        (HumanBoneType.LeftLowerArm, HumanBoneType.LeftHand),
        //
        (HumanBoneType.UpperChest, HumanBoneType.RightShoulder),
        (HumanBoneType.RightShoulder, HumanBoneType.RightUpperArm),
        (HumanBoneType.RightUpperArm, HumanBoneType.RightLowerArm),
        (HumanBoneType.RightLowerArm, HumanBoneType.RightHand),
        //
        (HumanBoneType.LeftHand, HumanBoneType.LeftThumbProximal),
        // (HumanBoneType.LeftThumbProximal, HumanBoneType.LeftThumbIntermediate),
        (HumanBoneType.LeftThumbMetacarpal, HumanBoneType.LeftThumbProximal),
        (HumanBoneType.LeftThumbProximal, HumanBoneType.LeftThumbDistal),
        (HumanBoneType.LeftHand, HumanBoneType.LeftIndexProximal),
        (HumanBoneType.LeftIndexProximal, HumanBoneType.LeftIndexIntermediate),
        (HumanBoneType.LeftIndexIntermediate, HumanBoneType.LeftIndexDistal),
        (HumanBoneType.LeftHand, HumanBoneType.LeftMiddleProximal),
        (HumanBoneType.LeftMiddleProximal, HumanBoneType.LeftMiddleIntermediate),
        (HumanBoneType.LeftMiddleIntermediate, HumanBoneType.LeftMiddleDistal),
        (HumanBoneType.LeftHand, HumanBoneType.LeftRingProximal),
        (HumanBoneType.LeftRingProximal, HumanBoneType.LeftRingIntermediate),
        (HumanBoneType.LeftRingIntermediate, HumanBoneType.LeftRingDistal),
        (HumanBoneType.LeftHand, HumanBoneType.LeftLittleProximal),
        (HumanBoneType.LeftLittleProximal, HumanBoneType.LeftLittleIntermediate),
        (HumanBoneType.LeftLittleIntermediate, HumanBoneType.LeftLittleDistal),
        //
        (HumanBoneType.RightHand, HumanBoneType.RightThumbProximal),
        // (HumanBoneType.RightThumbProximal, HumanBoneType.RightThumbIntermediate),
        (HumanBoneType.RightThumbMetacarpal, HumanBoneType.RightThumbProximal),
        (HumanBoneType.RightThumbProximal, HumanBoneType.RightThumbDistal),
        (HumanBoneType.RightHand, HumanBoneType.RightIndexProximal),
        (HumanBoneType.RightIndexProximal, HumanBoneType.RightIndexIntermediate),
        (HumanBoneType.RightIndexIntermediate, HumanBoneType.RightIndexDistal),
        (HumanBoneType.RightHand, HumanBoneType.RightMiddleProximal),
        (HumanBoneType.RightMiddleProximal, HumanBoneType.RightMiddleIntermediate),
        (HumanBoneType.RightMiddleIntermediate, HumanBoneType.RightMiddleDistal),
        (HumanBoneType.RightHand, HumanBoneType.RightRingProximal),
        (HumanBoneType.RightRingProximal, HumanBoneType.RightRingIntermediate),
        (HumanBoneType.RightRingIntermediate, HumanBoneType.RightRingDistal),
        (HumanBoneType.RightHand, HumanBoneType.RightLittleProximal),
        (HumanBoneType.RightLittleProximal, HumanBoneType.RightLittleIntermediate),
        (HumanBoneType.RightLittleIntermediate, HumanBoneType.RightLittleDistal),
    ];
}
