<Project>
  <PropertyGroup>
    <SpvDir>$(MSBuildProjectDirectory)/shaders/compiled</SpvDir>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.OperatingSystem]::IsWindows())">
    <Glslc>$(VULKAN_SDK)\Bin\glslc.exe</Glslc>
  </PropertyGroup>
  <PropertyGroup Condition="$([System.OperatingSystem]::IsLinux())">
    <Glslc>glslc</Glslc>
  </PropertyGroup>
</Project>
